import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi
import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import java.util.Properties

plugins {
    id("org.jetbrains.kotlin.multiplatform")
    id("com.android.kotlin.multiplatform.library")
    id("org.jetbrains.compose")
    id("org.jetbrains.kotlin.plugin.compose")
    id("org.jetbrains.kotlin.plugin.serialization")
}

/**
 * Google OAuth client IDs, read from (first match wins) a Gradle property, an environment
 * variable, or the git-ignored local.properties — e.g. `google.webClientId=123-abc.apps.googleusercontent.com`.
 * They aren't secrets (they ship inside every client), but they're per-deployment, so they stay
 * out of source control. Android needs no ID in code: its OAuth client is matched by package
 * name + signing certificate in Google Cloud Console.
 */
val localProperties = Properties().apply {
    rootProject.file("local.properties").takeIf { it.exists() }?.inputStream()?.use(::load)
}

fun googleSetting(property: String, env: String): Provider<String> =
    providers.gradleProperty(property)
        .orElse(providers.environmentVariable(env))
        .orElse(localProperties.getProperty(property) ?: "")

val generateGoogleClientConfig = tasks.register("generateGoogleClientConfig") {
    val webClientId = googleSetting("google.webClientId", "GOOGLE_WEB_CLIENT_ID")
    val iosClientId = googleSetting("google.iosClientId", "GOOGLE_IOS_CLIENT_ID")
    val outputDir = layout.buildDirectory.dir("generated/googleClientConfig/kotlin")
    inputs.property("webClientId", webClientId)
    inputs.property("iosClientId", iosClientId)
    outputs.dir(outputDir)
    doLast {
        val file = outputDir.get().file("org/neteinstein/snap2sheet/data/auth/GoogleClientConfig.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |package org.neteinstein.snap2sheet.data.auth
            |
            |/** Generated by the `generateGoogleClientConfig` Gradle task — see composeApp/build.gradle.kts. */
            |internal object GoogleClientConfig {
            |    const val WEB_CLIENT_ID: String = "${webClientId.get().trim()}"
            |    const val IOS_CLIENT_ID: String = "${iosClientId.get().trim()}"
            |}
            |""".trimMargin()
        )
    }
}

kotlin {
    jvmToolchain(17)

    sourceSets.all {
        languageSettings.optIn("kotlin.time.ExperimentalTime")
        languageSettings.optIn("kotlin.uuid.ExperimentalUuidApi")
        languageSettings.optIn("kotlin.io.encoding.ExperimentalEncodingApi")
        when {
            name.startsWith("ios") -> {
                languageSettings.optIn("kotlinx.cinterop.ExperimentalForeignApi")
                languageSettings.optIn("kotlinx.cinterop.BetaInteropApi")
            }
            name.startsWith("wasmJs") -> languageSettings.optIn("kotlin.js.ExperimentalWasmJsInterop")
        }
    }

    @OptIn(ExperimentalKotlinGradlePluginApi::class)
    android {
        namespace = "org.neteinstein.snap2sheet.shared"
        compileSdk = 36
        minSdk = 24

        withHostTestBuilder {}.configure {}
        withDeviceTestBuilder {
            sourceSetTreeName = "test"
        }

        androidResources {
            enable = true
        }
    }

    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
        }
    }

    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        outputModuleName = "composeApp"
        browser {
            commonWebpackConfig {
                outputFileName = "composeApp.js"
            }
        }
        binaries.executable()
    }

    sourceSets {

        commonMain {
            kotlin.srcDir(generateGoogleClientConfig)
        }

        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.ui)
            implementation(compose.components.resources)
            implementation(compose.components.uiToolingPreview)
            implementation(libs.androidx.lifecycle.viewmodel)
            implementation(libs.androidx.lifecycle.runtime.compose)
            implementation(libs.androidx.navigation.compose)
            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.kotlinx.datetime)
            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.serialization.kotlinx.json)
            implementation(libs.coil.compose)
            implementation(libs.coil.network.ktor)
            implementation(libs.koin.core)
            implementation(libs.koin.compose)
            implementation(libs.koin.compose.viewmodel)
        }

        androidMain.dependencies {
            implementation(libs.kotlinx.coroutines.android)
            implementation(libs.ktor.client.okhttp)
            implementation(libs.koin.android)
            implementation(libs.androidx.credentials)
            implementation(libs.androidx.credentials.play.services.auth)
            implementation(libs.googleid)
            implementation(libs.androidx.activity.compose)
            implementation(libs.androidx.core.ktx)
            implementation(libs.androidx.work.runtime)
            implementation(libs.androidx.exifinterface)
            implementation(libs.play.services.auth)
            implementation(libs.kotlinx.coroutines.play.services)
            implementation(libs.camerax.camera2)
            implementation(libs.camerax.lifecycle)
            implementation(libs.camerax.view)
            implementation(libs.mlkit.barcode.scanning)
        }

        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
        }

        wasmJsMain.dependencies {
            implementation(libs.ktor.client.js)
            implementation(libs.kotlinx.browser)
        }

        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.coroutines.test)
            implementation(libs.ktor.client.mock)
        }
    }
}
